---
- name: installing packages for python env
  become: true
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Creates directory
  file:
    path: ./basic-http-server
    state: directory

- name: install apache2
  become: true
  apt: name=apache2 update_cache=yes state=latest
