---
- name: Add PostgreSQL repository
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: absent

- name: Add PostgreSQL repository to sources list
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: absent

- name: Update apt cache
  apt:
    update_cache: yes

- name: Uninstalling PostgreSQL
  apt:
    name: "postgresql-*"
    state: absent
    purge: true
  
